name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps: 
      - name: Print a welcome message
        run: echo "Welcome to my Github profile" 

      - name: Checkout repo
        uses: actions/checkout@v3.7.0

      - name: List repo files
        run: ls -la
        
